services:
  postgres:
    image: postgres:latest
    container_name: bibletrack_postgres
    environment:
      POSTGRES_DB: bibletrack_db
      POSTGRES_USER: bibletrack_user
      POSTGRES_PASSWORD: bibletrack_pass
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8888:80" # Host_Port:Container_Port
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: strong_password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data: